# Generated by Django 5.2.6 on 2025-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_transaction_account_reference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True, help_text="Human-readable transaction note", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("loan_repayment", "Loan Repayment"),
                    ("savings", "Savings"),
                    ("loan_disbursement", "Loan Disbursement"),
                    ("pension_contribution", "Pension Contribution"),
                ],
                max_length=20,
            ),
        ),
    ]
