# Generated by Django 5.2.6 on 2025-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loanaccount_loan_reason_loanaccount_loan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccount",
            name="frequency_of_payment",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="repayment_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guarantor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="loan_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_GUARANTOR", "Pending Guarantor Approval"),
                    ("PENDING_MANAGER", "Pending Manager Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("DISBURSED", "Disbursed"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
