# Generated by Django 5.2.6 on 2025-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_loanaccount_frequency_of_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guarantor",
            name="guarantor_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="loan_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loanrepayment",
            name="repayment_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
